version: "3"

services:
  trojan:
    container_name: trojan
    image: p4gefau1t/trojan-go
    restart: always
    ports:
      - "443:443"
      - "443:443/udp"
    volumes:
        - ./config.json:/etc/trojan-go/config.json
        - /opt/cert:/opt/cert
    depends_on:
      - caddy
  caddy:
    image: caddy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./wwwroot:/usr/src
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./ssl:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory
